name: Dependency Scanning for Snyk and Trivy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk-scan:
    name: Snyk Dependency Scan for Python
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Adjust the version as needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Adjust if you have different requirements

      - name: Install Snyk CLI
        run: npm install -g snyk # Install Snyk globally

      - name: Authenticate Snyk
        run: snyk auth "${{ secrets.SNYK_TOKEN_2 }}" # Use the new SNYK_TOKEN_2 from GitHub Secrets

      - name: Run Snyk to check for vulnerabilities
        run: snyk test --all-projects --severity-threshold=medium # Adjust the severity threshold as needed

      - name: Monitor project in Snyk
        run: snyk monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN_2 }} # Use the new SNYK_TOKEN_2 here as well

  trivy-scan:
    name: Trivy Filesystem Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.35.0/trivy_0.35.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.35.0_Linux-64bit.deb

      - name: Cache Trivy DB
        uses: actions/cache@v3
        with:
          path: ~/.cache/trivy
          key: trivy-db-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }} # Ensure this matches your dependency file
          restore-keys: |
            trivy-db-${{ runner.os }}-

      - name: Run Trivy Filesystem Scan
        run: trivy fs --exit-code 0 .

